## Environment
- **Qiskit Terra version**: 0.43.1 meta package, terra 0.24.1
- **Python version**: 3.10
- **Operating system**: docker continuumio/miniconda3

## What is happening?
A circuit where a `QFT` is appended to a circuit and then exported to QASM, cannot be reimported because it produces an invalid qasm (with a recursive definition of the `gate_QFT`, not described anywhere).


## How can we reproduce the issue?
Run this python script:

```python
from qiskit import QuantumCircuit
from qiskit.circuit.library import QFT
qc = QuantumCircuit(2,2)
qc.append(QFT(2, do_swaps=False), [1,0])
qc.measure([1,0], [1,0])
print(qc.draw())

qc.qasm(filename="my.qasm")

QuantumCircuit.from_qasm_file("my.qasm").draw(output='mpl')
```
Produces this output and error:
```bash
     ┌──────┐   ┌─┐
q_0: ┤1     ├───┤M├
     │  QFT │┌─┐└╥┘
q_1: ┤0     ├┤M├─╫─
     └──────┘└╥┘ ║
c: 2/═════════╩══╩═
              1  0
...
  File "..../lib/python3.10/site-packages/qiskit/qasm/qasmparser.py", line 138, in verify_as_gate
    raise QasmError(
qiskit.qasm.exceptions.QasmError: "Cannot find gate definition for 'gate_QFT', line 3 file my.qasm"
```
The error happens only when importing the qasm file, whereas I believe the mistake is done by the exporter,

This is the genrated QASM:
```qasm
OPENQASM 2.0;
include "qelib1.inc";
gate gate_QFT q0,q1 { gate_QFT q0,q1; }
qreg q[2];
creg c[2];
gate_QFT q[1],q[0];
measure q[1] -> c[1];
measure q[0] -> c[0];

```

## What should happen?
I would have expected the QASM exporter to generate a valid qasm, ready to be reimported.

## Any suggestions?
This recursive definition of the `gate_QFT` is quite puzzling for me, looking forward to your feedback. I checked and with the `compose` API this problem des not happen: i.e. `qc.compose(QFT(2, do_swaps=False), [1,0], inplace=True)` produces a valid qasm file with `gate gate_QFT q0,q1 { h q1; cp(pi/2) q1,q0; h q0; }`.
